name: Pre-generated zip with all benchmarks

on: [push, pull_request]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: qasm_files/ae_indep_2.qasm results.csv
          recursive: false
          dest: ./MQTBench_all.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/result.zip